name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [17]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Install Playwright dependencies
      run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"

    - name: Install browsers
      run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install"

    - name: Run tests
      run: mvn clean test

    - name: Generate Allure Report
      if: always()
      run: mvn allure:report

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-report-${{ matrix.os }}
        path: target/site/allure-maven-plugin/
        retention-days: 30

    - name: Upload Test Screenshots
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-screenshots-${{ matrix.os }}
        path: target/screenshots/
        retention-days: 7