name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [17]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libatk1.0-0 \
          libasound2 \
          libatk-bridge2.0-0 \
          libatspi2.0-0 \
          libcairo2 \
          libcups2 \
          libdbus-1-3 \
          libdrm2 \
          libgbm1 \
          libglib2.0-0 \
          libnspr4 \
          libnss3 \
          libpango-1.0-0 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxcomposite1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxrandr2 \
          libxshmfence1 \
          fonts-noto-color-emoji \
          fonts-liberation \
          libcairo-gobject2 \
          libdbus-glib-1-2 \
          libgdk-pixbuf2.0-0 \
          libgtk-3-0 \
          libpangocairo-1.0-0 \
          libxcursor1 \
          libxi6 \
          libxtst6 \
          xvfb

    - name: Setup Maven on Windows
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        echo "$env:MAVEN_HOME/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "${{github.workspace}}/apache-maven-3.9.6/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install Playwright browsers
      run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

    - name: Run tests
      run: mvn clean test

    - name: Generate Allure Report
      if: always()
      run: mvn allure:report

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-${{ matrix.os }}
        path: target/site/allure-maven-plugin/
        retention-days: 30
        compression-level: 6
        overwrite: true

    - name: Upload Test Screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-screenshots-${{ matrix.os }}
        path: target/screenshots/
        retention-days: 7
        compression-level: 6
        overwrite: true